targets: 
  $default: 
    builders: 
      rad|styles: 
        generate_for: 
         - lib/src/css/** 
        enabled: True 

builders: 
  styles: 
    import: 'src_builders/builders.dart' 
    builder_factories: ['styles'] 
    build_extensions: 
      .css: 
       - .generated.dart 
    build_to: source 
    auto_apply: root_package
