name: castor
description: A frontend framework for Dart
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'


# dependencies:
#   path: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^1.0.0
