name: tard
version: 0.0.2
description: A frontend framework for Dart.
homepage: https://github.com/erlage/tard
documentation: https://github.com/erlage/tard#readme

environment:
  sdk: '>=2.16.1 <3.0.0'

platforms:
  web:

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^1.0.0
