name: rad
version: 0.0.2
description: >
  A frontend framework for Dart. It's inspired from Flutter and shares same programming paradigm. Widgets in Rad are similar to Flutter widgets but in many ways more flexible.

homepage: https://github.com/erlage/rad
documentation: https://github.com/erlage/rad#readme

environment:
  sdk: '>=2.16.1 <3.0.0'

platforms:
  web:

dev_dependencies:
  build: ^2.2.1
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^1.0.0

